replicas: 2 # You can Change replicas in here 
image: rohammosalli/app1 
Imagetag: 'latest' # this part will be replacet in CI/CD 
ingressClass: nginx # you have a seperate Ingress for each namespace you can chnage it here
extraConfig: ""
namespace: b2c # if you want to deploy in another namespace you can chage it here



#if you want access to this app you shuld add your source ip in here (find your IP "curl ifconfig.ca")
whitelist: 51.158.191.230/32

service:
  type: ClusterIP
  port: 8080

# This pars can help us to update or app without any Downtime, the most common SRE aspect for zero 
# downtime says we can use Blue/Green or  Canary Deployment to make our app HA, But I just Used RollingUpdate so it's close 
strategy:
  type: RollingUpdate
  rollingUpdate:
  maxSurge: 1
  maxUnavailable: 25%


#If you have any change in ingress like changing the path our adding annotations you work with this pars

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
  path: /app1
  hosts:
    - app1.pinsvc.net

